### ISSUE TITLE
Sure could use an update for 'No Boundary Limits' SP

### ISSUE THREAD

**Issue by mistahwolf** [alloc8or/gta5-nativedb-data#235]
Greetings. I'm a long time fan and user of NBL. It seriously needs an update! As of the 'Contract' DLC, NBL works except for the 'Depth Limit.' When selected 'true' in the ini, you can dive down infinitely (if you can even get into the water walking, diving in or sinking). But, if you try to go into any multiplayer MLO that's under the map, you get 'ported back to the surface. The discrepancy started when you added allowing submersible vehicles to go below 200ft. Please remove this feature if you can (or will) update the mod as it causes more problems.
Thank you for your time.

**Comment by kagikn** [comment]
Completely unrelated to this project. Even if there are no appropriate and active places to give some feedbacks about No Boundary Limits on 5Mods, this is definitely not an appropriate place for those feedbacks.

**Comment by mistahwolf** [comment]
"Completely unrelated to this project. Even if there are no appropriate and active places to give some feedbacks about No Boundary Limits on 5Mods, this is definitely not an appropriate place for those feedbacks._"

(sigh)
Unfortunately, this was the only place to bring this issue to your attention since you no longer answer inquiries at 5Mods. I looked for a way to start an inquiry separate from this, but found no avenue. If you would be so kind, please direct me to where and or how to set up said inquiry about 'No Boundary Limits' instead of a 'lecture' concerning 'appropriate places for feedbacks'. 
Respectfully,
Mistahwolf.

**Comment by kagikn** [comment]
I believe we cannot get alloc8or to have No Boundary Limits updated in any way. He haven't updated any his mods since July 2022 iirc. However we start an inquiry about his mods, he will not be going to update some of his mods, I believe.

But to be honest, it would have been better if you tried some of the contacts listed in [his page](https://alloc8or.re) before this issue was created. I haven't tried since I haven't had any questions (unrelated to the Native DB) to ask him since he left the 5Mods Discord server though.

**Comment by kagikn** [comment]
Since I'm assuming you would like to say something more to claim an updated version of No Boundary Limits in this issue, let's see if @alloc8or or @fingaweg closes it as not planned and locks the conversation…

For No Boundary Limits, I would say you can just hope someone will manage to create scripts with some of the equivalent features or update No Boundary Limits by reverse engineering. alloc8or isn't paid to update the mod at least. No one can claim the copyright of info about game memory stuff you found, and anyone can use some of them without express permission (unless R* or T2 bother sending DMCA takedown notices to some of our mods for using said info, unfortunately).
